[global]
developmentMode = false

[server]
headless = true
fileWatcherType = "auto"

[browser]
gatherUsageStats = false

[logger]
level = "error"
messageFormat = "%(asctime)s %(levelname)s %(message)s"
