[global]
developmentMode = false

[server]
headless = true
fileWatcherType = "auto"
# روی کلود نیازی به address/port نیست

[browser]
gatherUsageStats = false

[logger]
level = "error"            # لاگ‌ها را تمیز می‌کند
messageFormat = "%(asctime)s %(levelname)s %(message)s"
